dev:
  JWT_SECRET: dev/auth/jwt
  USERS_TABLE: users-table
  RAPIDAPI_KEY: dev/rapidapikey
  FUND_TRACKING_TABLE: mutual-fund-tracking-table
  PORTFOLIO_TABLE: portfolio-table
  PORTFOLIO_VALUE_TABLE: portfolio-update-table

#uat:
#  JWT_SECRET: uat/auth/jwt


#prod:
#  JWT_SECRET: prod/auth/jwt
