dev:
  JWT_SECRET: dev/auth/jwt
  USERS_TABLE: users-table
  RAPIDAPI_KEY: 3604ca55e9msh076324190b6d4bap17e118jsn2f6c159748b2
  FUND_TRACKING_TABLE: mutual-fund-tracking-table
  PORTFOLIO_TABLE: portfolio-table
  PORTFOLIO_VALUE_TABLE: portfolio-update-table

#uat:
#  JWT_SECRET: uat/auth/jwt


#prod:
#  JWT_SECRET: prod/auth/jwt
